version: '3'
services:
  web:
    build: .
    container_name: ${DOCKER_YTDL}
    ports:
      - "56000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
  mongo:
    container_name: ${DOCKER_YTDLDB}
    image: mongo
    ports:
      - "56001:27017"
    restart: unless-stopped
  redis:
    image: redis
    container_name: ${DOCKER_YTDLREDIS}
    ports:
      - "56002:6379"
    restart: unless-stopped
  meilisearch:
    image: getmeili/meilisearch:v1.4
    container_name: ${DOCKER_YTDLMEILI}
    ports:
      - "56003:7700"
    restart: unless-stopped
    volumes:
      - ./meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
