version: '3'
services:
  web:
    build: .
    container_name: ytdl
    ports:
      - "56000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    container_name: ytdldb
    image: mongo
    ports:
      - "56001:27017"