version: '3'
services:
  web:
    build: .
    container_name: ytdl
    ports:
      - "56000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
  mongo:
    container_name: ytdldb
    image: mongo
    ports:
      - "56001:27017"
    restart: unless-stopped
  redis:
    image: redis
    container_name: ytdlredis
    ports:
      - "56002:6379"
    restart: unless-stopped